import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-white dark:bg-gray-950 scheme-light dark:scheme-dark"
    >
      <body className="layout">
        <header>
          <nav>{/* navbar */}</nav>
        </header>
        {children}
        <footer>
          <p>&copy; 2025 Mias Bakery</p>
        </footer>
      </body>
    </html>
  );
}
